### ISSUE TITLE
continuous build for taxonworks:latest

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/install_taxonworks#19]
In general this would be perfect:

```
  when I test green on development branch
     then I rebuild taxonworks:latest
         and I push the container to https://hub.docker.com/r/sfgrp/taxonworks/
```

**Comment by jhpoelen** [comment]
ok, it does seem like I need more access than just push access to enable travis.

```console
$ travis enable
not allowed to update service hook for SpeciesFileGroup/install_taxonworks
```

**Comment by mjy** [comment]
Made you admin here.

**Comment by jhpoelen** [comment]
@mjy thanks.

As far as I can tell, taxonworks supports two product configurations: taxonworks-dev (for development) and taxonworks (for production). The former is historically only built locally whereas the latter is pushes for latest and specific release versions. This split is reflected in the install_taxonworks/development and taxonworks/production directories.

The taxonworks-dev consists of roughly two things: a base image with bunch of dependencies (e.g., ruby, postgres, apt libs) and a version of the taxonworks ruby app.  The taxonworks (production) also has these two things, only the base image is different.

To no slow down the existing travis build (already takes ~30 min), I'd suggest to do the following:

1. in separate repositories (taxonworks-base/taxonworks-base-dev), define docker files with the base images for dev and prod. These docker files are pushed periodically (every day?) and keep track of the changes pulled in by apt update and docker images. Names of the images are taxonworks-base-dev and taxonworks-base, the same as the repository names.

2. in taxonworks, let the two dev/prod docker files based on the base images from 1. After passing tests, Push to taxonworks-dev:latest and taxonworks:latest for respective products and deploy taxonworks:[some version] on cutting a release. 

3. move the ```docker-compose.yml``` into install_taxonwords because the compose depends on the docker images produced by the taxonworks repository. 

This makes sense to me, and I am sure that there's some historic aspects that I might not be aware of.

Here's the repos I've used to implement a prototype of this idea:

https://github.com/jhpoelen/taxonworks
https://github.com/jhpoelen/taxonworks-base
https://github.com/jhpoelen/taxonworks-base-dev
https://github.com/jhpoelen/install_taxonworks

Curious to hear your thoughts - I'd be happy to create some pull requests if you'd like to incorporate these changes. The only thing you'd have to do is create taxonworks-base taxonworks-base-dev repositories in docker hub and set the DOCKER_USERNAME and DOCKER_PASSWORD environment veriables for taxonworks, taxonworks-base and taxonworks-base-dev repositories.

**Comment by mjy** [comment]
I have to focus on your interpretation a bit more, but will spam this now:

# using `docker build ....`:

* taxonworks:latest is always a development release, build locally against the `development` branch, pushed by us (the only thing preventing automatic pushes was detecting the green tests)

* taxonworks:x.y.z is always a production release against the `master` branch, will remain a manual push... I think

# using `docker-compose up`

* Build on any branch, against `Dockerfile.development`, intent was getting a local environment up against a (semi) persistent database, allowing real-time dev against containers, particularly useful when using the API and developing against it

**Comment by mjy** [comment]
Clarification question-

Are you proposing we pull down a base image to travis, to be used in spec runs when pushes to `development` branch occur?

**Comment by jhpoelen** [comment]
I imagine it would be wise to run the tests in the base image. This is not been setup yet. Also, I'd have to tweak some settings to account for the magic branches (main vs. development). As far as releases go, you can setup a separate flow for tagged commits (aka releases) and inherit the tag/release strings/numbers.

**Comment by mjy** [comment]
Saw that you're trying to use `Dockerfile.development` in travis against development- this won't quite work as you intend I think, in part there is no database persistent in travis.

**Comment by jhpoelen** [comment]
Right now, CI on my fork of taxonworks attempts to - (a) build dev and prod docker images (b) run the tests (not yet in the container) and (c) push the images on passing tests.

**Comment by jhpoelen** [comment]
Let me know if you'd like to discuss by voice.

**Comment by mjy** [comment]
I would, but in workshop.

https://github.com/jhpoelen/taxonworks/blob/development/.travis.yml#L39

Use `Dockerfile`, not `Dockerfile.development`.

**Comment by jhpoelen** [comment]
ok, did you notice the next line? 
https://github.com/jhpoelen/taxonworks/blob/development/.travis.yml#L40 ? 

There's two images being built for the two difference taxonworks "products". Made the default explicit using ```-f Dockerfile```

**Comment by jhpoelen** [comment]
Just to document some updates shared over video chat:

1. base docker images introduced to allow test images built off of production images (e.g., see https://github.com/jhpoelen/taxonworks-base )
2. in taxonworks fork at https://github.com/jhpoelen/taxonworks , all but 4 tests tests pass (including ui and integration tests) in dockerized docker-compose environment (see attached build log). 
3. enabled automated deployment to hub.docker.com using travis config. 

Next steps include introducing docker images in speciesfilegroup org and creating a pull request for taxonworks project with containerized tests. 

[log.txt](https://github.com/SpeciesFileGroup/install_taxonworks/files/2480410/log.txt)

**Comment by jhpoelen** [comment]
I noticed that the travis build is now disabled after about 2 years to automated building and pushing of Docker images (see https://github.com/SpeciesFileGroup/install_taxonworks/pull/22/commits/ec184d5a78e0f0abbbdc09b94ad046862f354aca ). Does this mean that the idea of automated image building has been abandoned? If so, I think this issue can be closed.

**Comment by LocoDelAssembly** [comment]
@jhpoelen at https://github.com/SpeciesFileGroup/taxonworks/ Travis CI (and now GitHub Actions) build both the latest (refreshed on every push), and versioned tags on new version release.

Does this cover the goals in here?

Had to disable Travis CI because free beer is over. We could rewrite this for GitHub Actions if needed, beer is free here.
